### ISSUE TITLE
Change text on the fly

### ISSUE THREAD

**Issue by luigi37** [valnub/Framework7-Upscroller-Plugin#11]
Hi,
is there a way to change the text on the fly? I'd need to be able to change the text based on user language...
Thanks
Luigi

**Comment by valnub** [comment]
Hm, try this:

```javascript
var label = 'YOUR TEXT'; // <-- Add your custom label here
Dom7('.upscroller').text('↑ ' + label);
```

**Comment by luigi37** [comment]
Thank you! Will give a try tonight!

**Comment by luigi37** [comment]
Cool! Works like a charm!
