### ISSUE TITLE
mainView is not defined error on click

### ISSUE THREAD

**Issue by luigi37** [valnub/Framework7-Upscroller-Plugin#12]
Hi, I'm using the version here
https://github.com/valnub/Framework7-Upscroller-Plugin/tree/master/src

It gives error when clicking: "mainView" is not defined.

Copying from other versions I changed from
 var curpage = $$(".page-content", mainView.activePage.container);
to
 var curpage = $$(".page-content", app.getCurrentView().activePage.container);
and it works fine.

To be noted also that if I add:
if ($$("[data-page='"+pageData.name+"'] > .searchbar")[0]) $$("[data-page='"+pageData.name+"'] >  .upscroller").css('top', '-10px');

The blue button goes out of the view with search bar...

**Comment by valnub** [comment]
Can you post a [fiddle](http://jsfiddle.net) or [codepen](http://codepen.io) to show the error?

**Comment by luigi37** [comment]
Yes I can do it tonight, but I found a bit weird that if you pick the source files from two different locations in github repository the files are different.
Not only in mainView vs app.getCurrentView but also one has  the CCS top thing mentioned above and the other has not.
It looks like there are some row not fully aligned...
Luigi

**Comment by valnub** [comment]
Did you solve the problem ?
