### ISSUE TITLE
Update code to work with multiple views app

### ISSUE THREAD

**Issue by galebnas** [valnub/Framework7-Upscroller-Plugin#5]
Hi and thank you very much for this plugin :)

please update the code of the plugin at the line 16 to be:

var curpage = $$(".page-content", app.getCurrentView().activePage.container);  
this will help the plugin to work with multiple views apps

Thank you again

**Comment by valnub** [comment]
PR? :)

**Comment by galebnas** [comment]
I made one PR for both issues the search bar and the multiple views

https://github.com/valnub/Framework7-Upscroller-Plugin/pull/7

**Comment by valnub** [comment]
Alrighty, closed
