### ISSUE TITLE
Update code to work with Searchbar

### ISSUE THREAD

**Issue by galebnas** [valnub/Framework7-Upscroller-Plugin#6]
Again thank you for the great plugin.

Just add this line of code after line 11
if ($$("[data-page='"+pageData.name+"'] > .searchbar")[0]) $$('.upscroller').css('top', '-10px');

this will make the upscroller div appear below the Searchbar not over it.

**Comment by valnub** [comment]
Can you open a PR?

**Comment by galebnas** [comment]
Sure https://github.com/valnub/Framework7-Upscroller-Plugin/pull/7

**Comment by valnub** [comment]
Thanks, I'll check it out

**Comment by valnub** [comment]
Merged

**Comment by tinyCoder32** [comment]
hey Timo, you need to fix it for sub navbar too, it is showing beneath it, you can't click it.

**Comment by tinyCoder32** [comment]
Sorry, false alarm :(
I used the JS code found in:
https://github.com/valnub/Framework7-Upscroller-Plugin/tree/master/src

It seems older than the recent code.
